name: simple_searching_flutter_algorithms
description: This package provides three search functions Binary Search, Linear Search, and Jump Search.
version: 0.0.3
repository: https://github.com/TojiddinovMuhammadabdullox/simple_searching_flutter_algorithms


environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0



